### ISSUE TITLE
What is the license of this project?

### ISSUE THREAD

**Issue by jmini** [OpenAPITools/openapi-petstore#4]
@cbornet: I have noticed that we have no license information in this repository. Can we agree to set it to Apache 2.0?
(I can file a PR to add it, but I would like to record an agreement in this issue before)

cc: @wing328

**Comment by cbornet** [comment]
:+1:

**Comment by wing328** [comment]
Good catch! Your suggestion sounds good to me.

(auto-generated code by openapi-generator is unlicensed by default)

**Comment by jmini** [comment]
PR for this: https://github.com/OpenAPITools/openapi-petstore/pull/5
